const state={token:sessionStorage.getItem('mailops_token')||'',email:sessionStorage.getItem('mailops_email')||'',requests:[],builds:[],template:null,autoReply:null,selected:null,health:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function decodeHtml(v=''){const el=document.createElement('textarea');el.innerHTML=String(v);return el.value;}
function inferName(email=''){return String(email).split('@')[0].replace(/[._+-]+/g,' ').trim()||email;}
function fillTemplate(value,vars){let out=decodeHtml(value||'');Object.entries(vars).forEach(([k,v])=>{out=out.split(`{${k}}`).join(String(v??''));});return out;}
function fmt(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function labelStatus(v){return({pending:'待处理',reviewing:'审核中',approved:'已批准',sent:'已发送',rejected:'已拒绝',archived:'已归档'})[v]||v;}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200);}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization='Bearer '+state.token;const res=await fetch(path,{...options,headers});let data={};try{data=await res.json();}catch(_){data={error:'服务返回异常'};}if(res.status===401&&path!='/api/auth/login'){logout();throw new Error('登录已过期，请重新登录');}if(!res.ok)throw new Error(data.error||`请求失败 (${res.status})`);return data;}
function setAuth(token,email){state.token=token||'';state.email=email||'';if(token){sessionStorage.setItem('mailops_token',token);sessionStorage.setItem('mailops_email',email);}else{sessionStorage.removeItem('mailops_token');sessionStorage.removeItem('mailops_email');}}
function logout(){setAuth('','');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');}
async function login(email,password){const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});setAuth(result.idToken,result.email);await enterApp();}
async function enterApp(){try{state.health=await api('/api/health');await Promise.all([loadSummary(),loadRequests(),loadBuilds(),loadTemplate(),loadAutoReply()]);$('#operatorEmail').textContent=state.email;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderMailStatus();route();}catch(e){if(state.token)toast(e.message,true);}}
function renderMailStatus(){const el=$('#mailStatus');if(state.health?.mailConfigured){el.className='status-chip ok';el.innerHTML='<span></span> 邮件通道在线';}else{el.className='status-chip bad';el.innerHTML='<span></span> 邮件通道未配置';}}
async function loadSummary(){const d=await api('/api/summary');const c=d.counts||{};$('#metricPending').textContent=c.pending||0;$('#metricReviewing').textContent=c.reviewing||0;$('#metricSent').textContent=c.sent||0;$('#metricBuilds').textContent=d.activeBuilds||0;$('#navPending').textContent=c.pending||0;}
async function loadRequests(){const q=$('#requestSearch')?.value||'';const status=$('#statusFilter')?.value||'all';const d=await api(`/api/requests?status=${encodeURIComponent(status)}&q=${encodeURIComponent(q)}`);state.requests=d.items||[];renderRequests();}
function renderRequests(){const el=$('#requestList');if(!state.requests.length){el.innerHTML='<div class="empty-state">没有符合条件的请求</div>';return;}el.innerHTML=state.requests.map(r=>`<article class="request-item ${state.selected===r.id?'active':''}" data-id="${escapeHtml(r.id)}"><div class="request-item-top"><b>${escapeHtml(r.email)}</b><time>${fmt(r.created_at)}</time></div><p>${escapeHtml(r.machine||r.note||'未提供机器信息')}</p><span class="tag ${escapeHtml(r.status)}">${labelStatus(r.status)}</span></article>`).join('');$$('.request-item').forEach(el=>el.onclick=()=>selectRequest(el.dataset.id));}
async function selectRequest(id){state.selected=id;renderRequests();const item=await api('/api/requests/'+encodeURIComponent(id));renderDetail(item);renderSend(item);if(innerWidth<781)document.querySelector('.detail-panel').style.display='block';}
function renderDetail(r){const events=(r.events||[]).map(e=>`<div class="timeline-item"><b>${escapeHtml(eventName(e.kind))}</b><span>${fmt(e.created_at)} · ${escapeHtml(e.actor)}</span></div>`).join('')||'<p class="muted">暂无记录</p>';const name=r.recipient_name||inferName(r.email);$('#requestDetail').innerHTML=`<div class="panel-head"><div><p class="eyebrow">REQUEST DETAIL</p><h3>申请详情</h3></div><span class="tag ${escapeHtml(r.status)}">${labelStatus(r.status)}</span></div><div class="detail-content"><div class="detail-title"><div><p class="eyebrow">REQUESTER</p><h3>${escapeHtml(name)}</h3><p>${escapeHtml(r.email)} · ${escapeHtml(r.id)}</p></div><div class="detail-actions"><button class="ghost small" id="markReview">标记审核</button><button class="ghost small" id="rejectRequest">拒绝</button></div></div><div class="info-grid"><div class="info-block"><span>机器 / 环境</span><b>${escapeHtml(r.machine||'未提供')}</b></div><div class="info-block"><span>提交时间</span><b>${fmt(r.created_at)}</b></div><div class="info-block full"><span>申请备注</span><b>${escapeHtml(r.note||'没有备注')}</b></div></div><div class="subhead">内部备注</div><textarea id="internalNote" class="internal-note" rows="3" placeholder="仅管理员可见">${escapeHtml(r.internal_note||'')}</textarea><div class="save-row"><button id="saveRequest" class="ghost small">保存</button></div><div class="subhead">TIMELINE</div><div class="timeline">${events}</div></div>`;$('#markReview').onclick=()=>updateRequest(r.id,{status:'reviewing'});$('#saveRequest').onclick=()=>updateRequest(r.id,{internal_note:$('#internalNote').value});$('#rejectRequest').onclick=()=>rejectRequest(r.id);}
function defaultReplyKind(r){const machine=(r.machine||'').toLowerCase();if(/\b(?:rtx|rtz)\s*[- ]?\d/.test(machine))return 'qualified';if(/\bgtx\s*[- ]?\d/.test(machine))return 'incompatible';if(/android|tablet|iphone|\bios\b|\ba0?5\b|vivo|galaxy|samsung|oppo|xiaomi|redmi/.test(machine))return 'mobile';return 'qualification';}
function replyPreset(r,kind){const name=r.recipient_name||inferName(r.email);const machine=r.machine||'Not provided';if(kind==='qualified')return{subject:'We’re reviewing your DLSS5 Studio request',body:`Hi ${name},\n\nThanks for requesting access to DLSS5 Studio. Your ${machine} setup matches the Windows + NVIDIA RTX profile we are currently reviewing.\n\nWe are not sending a software package yet because the authorised build is still being prepared. We have marked your request as high priority and will send a private link when a suitable build is ready.\n\nIf you reply, please tell us which games or workflow you want to test and what kind of feedback you can provide.\n\n— DLSS5 Studio`};if(kind==='mobile')return{subject:'About your DLSS5 Studio request',body:`Hi ${name},\n\nThanks for your download request. The device listed on your request is ${machine}. DLSS requires a compatible Windows PC with an NVIDIA RTX graphics card; it cannot be installed as an Android or iOS app.\n\nWe have not sent a download package because it would not work on the listed device. If you also have a Windows PC with an RTX GPU, reply with the Windows version and exact GPU model and we will review your request again.\n\n— DLSS5 Studio`};if(kind==='incompatible')return{subject:'Compatibility update for your DLSS5 Studio request',body:`Hi ${name},\n\nThanks for your download request. The graphics card listed on your request is ${machine}. The current workflow requires an NVIDIA RTX graphics card; GTX models are not compatible.\n\nWe have not sent a package because it would not work on the listed system. If you also have a Windows PC with an RTX GPU, reply with the exact model and we will review your request again.\n\n— DLSS5 Studio`};return{subject:'A quick question about your DLSS5 Studio request',body:`Hi ${name},\n\nThanks for requesting access to DLSS5 Studio. Before we send any software, we need to confirm that your system is compatible.\n\nPlease reply with:\n1. Your Windows version\n2. Your exact NVIDIA GPU model\n3. The game or workflow you want to use\n\nOnce we have those details, we can review the appropriate next step.\n\n— DLSS5 Studio`};}
function applyReplyPreset(r){const preset=replyPreset(r,$('#replyKind').value);$('#replySubject').value=preset.subject;$('#replyBody').value=preset.body;}
function renderSendPreview(r){const build=state.builds.find(b=>b.id===Number($('#sendBuild')?.value));const vars={recipient_name:r.recipient_name||inferName(r.email),email:r.email,machine:r.machine||'Not specified',note:r.note||'',build_name:build?`${build.name} ${build.version}`.trim():'未选择构建',download_url:'发送时自动生成私有链接',expires_hours:$('#expiresHours')?.value||'72'};$('#sendPreviewSubject').textContent=fillTemplate(state.template?.subject,vars)||'—';$('#sendPreviewBody').textContent=fillTemplate(state.template?.body,vars)||'—';}
function renderSend(r){const active=state.builds.filter(b=>b.active);const opts=active.map(b=>`<option value="${b.id}">${escapeHtml(b.name)} ${escapeHtml(b.version)}</option>`).join('');const disabled=!state.health?.mailConfigured||!active.length||r.status==='rejected';const replyDisabled=!state.health?.mailConfigured||r.status==='rejected'||Boolean(r.last_reply_at);const replyKind=defaultReplyKind(r);$('#sendPanel').innerHTML=`<div class="panel-head"><div><p class="eyebrow">CUSTOMER RESPONSE</p><h3>客户回复</h3></div></div><form class="send-form reply-form" id="replyForm"><label>回复类型<select id="replyKind"><option value="qualified" ${replyKind==='qualified'?'selected':''}>Windows + RTX 高意向</option><option value="mobile" ${replyKind==='mobile'?'selected':''}>移动端兼容性说明</option><option value="incompatible" ${replyKind==='incompatible'?'selected':''}>GTX 不兼容说明</option><option value="qualification" ${replyKind==='qualification'?'selected':''}>补充设备信息</option></select></label><label>邮件主题<input id="replySubject" maxlength="200"></label><label>正文<textarea id="replyBody" rows="12" maxlength="8000"></textarea></label><div class="send-note">${r.last_reply_at?'该客户已发送过申请回复，系统已锁定重复发送。':'仅回复本次下载申请，不会生成下载链接或发送验证包。'}</div><button class="primary" type="submit" ${replyDisabled?'disabled':''}>${r.last_reply_at?'已发送回复':'确认并发送回复 ↗'}</button></form><div class="panel-head delivery-head"><div><p class="eyebrow">DELIVERY ACTION</p><h3>正式构建交付</h3></div></div><form class="send-form" id="sendForm"><label>选择构建<select id="sendBuild" ${active.length?'':'disabled'}>${opts||'<option>暂无可用构建</option>'}</select></label><div class="form-pair"><label>有效期（小时）<input id="expiresHours" type="number" min="1" max="720" value="72"></label><label>最多下载次数<input id="maxDownloads" type="number" min="1" max="100" value="3"></label></div><div class="delivery-preview"><small>自动生成的邮件</small><h4 id="sendPreviewSubject">—</h4><pre id="sendPreviewBody">—</pre></div><div class="send-note ${state.health?.mailConfigured?'':'warn'}">${state.health?.mailConfigured?'仅在正式构建准备完成后使用。':'邮件通道尚未配置，发送功能已锁定。'}</div><button class="primary" type="submit" ${disabled?'disabled':''}>确认并发送构建 ↗</button></form>`;$('#replyKind').onchange=()=>applyReplyPreset(r);applyReplyPreset(r);$('#replyForm').onsubmit=e=>{e.preventDefault();sendReply(r.id);};$('#sendBuild').onchange=()=>renderSendPreview(r);$('#expiresHours').oninput=()=>renderSendPreview(r);renderSendPreview(r);$('#sendForm').onsubmit=e=>{e.preventDefault();sendRequest(r.id);};}
async function updateRequest(id,payload){try{const r=await api('/api/requests/'+id,{method:'PATCH',body:JSON.stringify(payload)});toast('请求已更新');await Promise.all([loadRequests(),loadSummary()]);await selectRequest(r.id);}catch(e){toast(e.message,true);}}
async function rejectRequest(id){const reason=prompt('请输入拒绝原因（内部记录）：','信息不足');if(reason===null)return;try{await api(`/api/requests/${id}/reject`,{method:'POST',body:JSON.stringify({reason})});toast('请求已拒绝');await Promise.all([loadRequests(),loadSummary()]);await selectRequest(id);}catch(e){toast(e.message,true);}}
async function sendRequest(id){const btn=$('#sendForm button[type=submit]');btn.disabled=true;btn.textContent='正在生成链接并发送…';try{await api(`/api/requests/${id}/send`,{method:'POST',body:JSON.stringify({build_id:Number($('#sendBuild').value),expires_hours:Number($('#expiresHours').value),max_downloads:Number($('#maxDownloads').value)})});toast('交付邮件已发送');await Promise.all([loadRequests(),loadSummary()]);await selectRequest(id);}catch(e){toast(e.message,true);btn.disabled=false;btn.textContent='确认并发送邮件 ↗';}}
async function sendReply(id){const btn=$('#replyForm button[type=submit]');btn.disabled=true;btn.textContent='正在发送回复…';try{await api(`/api/requests/${id}/reply`,{method:'POST',body:JSON.stringify({kind:$('#replyKind').value,subject:$('#replySubject').value,body:$('#replyBody').value})});toast('客户回复已发送');await Promise.all([loadRequests(),loadSummary()]);await selectRequest(id);}catch(e){toast(e.message,true);btn.disabled=false;btn.textContent='确认并发送回复 ↗';}}
async function loadBuilds(){const d=await api('/api/builds');state.builds=d.items||[];renderBuilds();}
function renderBuilds(){const el=$('#buildGrid');if(!state.builds.length){el.innerHTML='<div class="panel empty-state">暂无构建。添加第一个可交付版本。</div>';return;}el.innerHTML=state.builds.map(b=>`<article class="panel build-card"><div class="build-card-top"><div><p class="eyebrow">BUILD #${b.id}</p><h4>${escapeHtml(b.name)} ${escapeHtml(b.version)}</h4><p>${escapeHtml(b.platform)} · ${escapeHtml(b.gpu)}</p></div><button class="toggle ${b.active?'':'off'}" data-build="${b.id}">${b.active?'ACTIVE':'PAUSED'}</button></div><dl><dt>目标 URL</dt><dd>${escapeHtml(b.download_url)}</dd><dt>校验值</dt><dd>${escapeHtml(b.checksum||'—')}</dd><dt>更新时间</dt><dd>${fmt(b.updated_at)}</dd></dl></article>`).join('');$$('[data-build]').forEach(x=>x.onclick=()=>toggleBuild(Number(x.dataset.build)));}
async function toggleBuild(id){const b=state.builds.find(x=>x.id===id);try{await api('/api/builds/'+id,{method:'PATCH',body:JSON.stringify({active:!b.active})});toast(b.active?'构建已暂停':'构建已启用');await Promise.all([loadBuilds(),loadSummary()]);}catch(e){toast(e.message,true);}}
async function loadTemplate(){state.template=await api('/api/template');$('#templateSubject').value=state.template.subject||'';$('#templateBody').value=state.template.body||'';renderTemplatePreview();}
function renderTemplatePreview(){const vals={recipient_name:'Alex Chen',email:'user@example.com',machine:'RTX 5090 / Windows 11',note:'Preview',build_name:'DLSS5 Studio 5.2.0',download_url:'https://download.alphanetplus.com/d/••••••••',expires_hours:'72'};$('#previewSubject').textContent=fillTemplate($('#templateSubject').value,vals)||'—';$('#previewBody').textContent=fillTemplate($('#templateBody').value,vals)||'—';}
async function saveTemplate(){try{state.template=await api('/api/template',{method:'PUT',body:JSON.stringify({subject:$('#templateSubject').value,body:$('#templateBody').value})});toast('模板已保存');}catch(e){toast(e.message,true);}}
async function loadAutoReply(){state.autoReply=await api('/api/auto-reply');renderAutoReply();}
function renderAutoReply(){if(!state.autoReply)return;$('#autoReplyEnabled').value=state.autoReply.enabled?'on':'off';$('#autoReplyInterval').value=state.autoReply.intervalMinutes||15;$('#autoReplyBatch').value=state.autoReply.batchSize||10;const last=state.autoReply.lastSentAt?fmt(state.autoReply.lastSentAt):'尚未自动发送';$('#autoReplyStatus').textContent=`等待回复 ${state.autoReply.awaitingReply||0} · 已自动回复 ${state.autoReply.autoReplied||0} · 失败 ${state.autoReply.failed||0} · 最近发送 ${last}`;}
async function saveAutoReply(){const btn=$('#saveAutoReplyBtn');btn.disabled=true;try{state.autoReply=await api('/api/auto-reply',{method:'PUT',body:JSON.stringify({enabled:$('#autoReplyEnabled').value==='on',intervalMinutes:Number($('#autoReplyInterval').value),batchSize:Number($('#autoReplyBatch').value)})});renderAutoReply();toast(state.autoReply.enabled?'自动回复已启用':'自动回复已暂停');}catch(e){toast(e.message,true);}finally{btn.disabled=false;}}
async function loadActivity(){const d=await api('/api/activity');const el=$('#activityList');el.innerHTML=(d.items||[]).map(e=>`<div class="activity-row"><time>${fmt(e.created_at)}</time><b>${escapeHtml(eventName(e.kind))}</b><code>${escapeHtml(e.detail||'—')}</code><span>${escapeHtml(e.actor)}</span></div>`).join('')||'<div class="empty-state">暂无操作记录</div>';}
function eventName(k){return({'request.received':'收到申请','request.updated':'更新申请','request.rejected':'拒绝申请','build.created':'创建构建','build.updated':'更新构建','template.updated':'更新模板','auto_reply.settings':'自动回复设置已更新','mail.sent':'构建邮件已发送','mail.reply_sent':'客户回复已发送','mail.auto_reply_sent':'自动回复已发送','mail.auto_reply_failed':'自动回复失败','mail.failed':'邮件发送失败','download.opened':'下载链接已使用'})[k]||k;}
function route(){const page=(location.hash||'#requests').slice(1);$$('.page').forEach(x=>x.classList.add('hidden'));const target=$('#'+page+'Page')||$('#requestsPage');target.classList.remove('hidden');$$('#nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=({requests:'下载请求',builds:'构建版本',template:'邮件模板',activity:'操作记录'})[page]||'下载请求';if(page==='activity')loadActivity();}
async function googleLogin(){try{const cfg=await api('/api/config');if(!window.firebase)throw new Error('Google 登录组件加载失败');if(!firebase.apps.length)firebase.initializeApp(cfg.firebase);const result=await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider());const token=await result.user.getIdToken();setAuth(token,result.user.email);await enterApp();}catch(e){$('#loginError').textContent=e.message||'Google 登录失败';}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const err=$('#loginError');err.textContent='';const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{await login($('#loginEmail').value,$('#loginPassword').value);}catch(ex){err.textContent=ex.message;}finally{btn.disabled=false;}};
$('#googleLogin').onclick=googleLogin;$('#logoutBtn').onclick=logout;window.addEventListener('hashchange',route);$('#refreshBtn').onclick=()=>Promise.all([loadSummary(),loadRequests()]).then(()=>toast('已刷新')).catch(e=>toast(e.message,true));
let searchTimer;$('#requestSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadRequests().catch(e=>toast(e.message,true)),250);};$('#statusFilter').onchange=()=>loadRequests().catch(e=>toast(e.message,true));
$('#newBuildBtn').onclick=()=>$('#buildDialog').showModal();$('#buildForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const data=Object.fromEntries(f.entries());try{await api('/api/builds',{method:'POST',body:JSON.stringify(data)});$('#buildDialog').close();e.currentTarget.reset();toast('构建已添加');await Promise.all([loadBuilds(),loadSummary()]);}catch(ex){toast(ex.message,true);}};
$('#saveTemplateBtn').onclick=saveTemplate;$('#templateSubject').oninput=renderTemplatePreview;$('#templateBody').oninput=renderTemplatePreview;$('#refreshActivityBtn').onclick=()=>loadActivity().then(()=>toast('已刷新')).catch(e=>toast(e.message,true));
$('#saveAutoReplyBtn').onclick=saveAutoReply;
if(state.token)enterApp();
